### ISSUE TITLE
Boot Error 0xc0000098 boot failed does not contain...

### ISSUE THREAD

**Issue by oktaykarakiya** [mordaut97/galaxy_book_s_driver_pack#1]
I have this issue, I did not manage to solve it, might this be caused by the new windows 11 arm64 image released?

**Comment by mordaut97** [comment]
Hey,

you can try adding the drivers to this image.
[Windows image](https://isofiles.bd581e55.workers.dev/Windows%2011/22000.194%20-%20October%202021%20(Initial)/en-us_windows_11_iot_enterprise_arm64_dvd_49c627ac.iso)

**Comment by oktaykarakiya** [comment]
Hey, i solved installing [this ](https://drive.google.com/file/d/1daZBaqncxsxcU2cfVhqVC0jiC-xA45yY/view?usp=share_link)ready image i found, then via ethernet and windows update I got the drivers working. Now everything is working allright. However thank you for your help :)
